### ISSUE TITLE
Mobile NixOS stage-1 software keyboard freezes on latest master version on PinePhone

### ISSUE THREAD

**Issue by Luflosi** [mobile-nixos/lvgui#15]
This is very similar to the issue I reported in https://github.com/NixOS/mobile-nixos/pull/574#issuecomment-1442313409.
Commit 3b0331a18f36c42f3caa91d02a12abd79c4139ff works fine on the PinePhone, while 15f05e68401f7e87a496d3fc7171fb2699310dea freezes.
I haven't checked the serial output yet. Should I do that?

Would you like me to test if a PR works on the PinePhone before it is merged? The PinePhone seems to be special in this regard.

**Comment by samueldr** [comment]
I might not have tested properly on unrotated touch. I just saw not long ago that it didn't work on another system.

The keyboard doesn't freeze though, the whole app crashes!

* * *


Oh no... Looking at the commit the problem is pretty obvious...

`libinput_event_pointer_get_absolute_x_transformed` in touch event... <b>`pointer_get`</b>. Ugh. I knew when writing the change that those functions (pointer vs. touch) were bug traps!

I verified only on rotated displays (two of them even!), anyway surely I wouldn't have bungled the already working case, right? (It wasn't a conscious gesture, it just happened to be that all targets of touch testing were rotated.)
